Explicit wait
svillegasz/protractor-workshop-2017 pull request #13
Opened 2017-10-09 16:12 UTC by svillegasz

2017-10-09 17:02 UTC, aperdomob requested changes
no necesitas agregar tantas esperas explicitas, realmente solo debería ser una

2017-10-10 03:22 UTC, jhenaoz approved these changes

2017-10-10 03:23 UTC, jhenaoz commented
hay muchos wait con un mismo valor 3000, DRY (dont repeat yourself) lo podes poner en un archivo de configuración si no estoy mal podes configurar un implicit wait por defecto.

2017-10-10 12:11 UTC, aperdomob requested changes

2017-10-10 12:11 UTC, aperdomob commented on src/page/ProductDetail.page.ts
> +  public addToCart(): promise.Promise<void> {
remove spaces

2017-10-10 12:11 UTC, aperdomob commented on src/page/OrderResume.page.ts
> +    await browser.wait(this.until.presenceOf(this.completeMessage), 3000);
I am not sure if you need this wait

2017-10-10 13:43 UTC, aperdomob requested changes

2017-10-10 13:43 UTC, aperdomob commented on src/page/MenuContent.page.ts
> +
remove line

2017-10-10 13:43 UTC, aperdomob commented on src/page/BankPayment.page.ts
> +    await browser.wait(this.until.presenceOf(this.confirmButton), 3000);
continuo con la duda, en teoría para que corra el test solo se necesita una espera explicita en `ProductAddedModal.page.ts` no logro entender porque tu necesitas una adicional

2017-10-10 13:45 UTC, svillegasz commented on src/page/BankPayment.page.ts
> +    await browser.wait(this.until.presenceOf(this.confirmButton), 3000);
jajaja ayer los estaba quitando pero aparentemente se me fueron algunos

2017-10-10 13:48 UTC, aperdomob requested changes

2017-10-10 13:48 UTC, aperdomob commented on src/page/MenuContent.page.ts
> +
falta este cambio

2017-10-10 13:54 UTC, aperdomob requested changes

2017-10-10 13:54 UTC, aperdomob commented on protractor/headless.config.ts
> +  onPrepare () {
este archivo tiene un error deberia ser algo como onPrepare: ()  => {
}

No se porque tslint no te saca error

2017-10-10 14:11 UTC, svillegasz commented on protractor/headless.config.ts
> +  onPrepare () {
Fue tslint el que me lo cambio, pero ya no me sale el error. Lo voy a volver a cambiar!

2017-10-10 14:49 UTC, aperdomob commented on protractor/headless.config.ts
> +  onPrepare () {
no conocia esa sintaxis para json :O

2017-10-10 14:50 UTC, aperdomob approved these changes

2017-10-10 14:55 UTC, merged