Upload file
svillegasz/protractor-workshop-2017 pull request #22
Opened 2017-10-12 03:08 UTC by svillegasz

2017-10-12 12:09 UTC, aperdomob requested changes

2017-10-12 12:09 UTC, aperdomob commented on src/page/IFrame.page.ts
> +import { $, ElementFinder, browser, promise } from 'protractor';
por que estos cambios en este PR

2017-10-12 12:09 UTC, aperdomob commented on src/page/PersonalInformation.page.ts
> +  private get photo(): ElementFinder {
que es esto, un input, un label, colocar el sufijo

2017-10-12 12:09 UTC, aperdomob commented on src/page/PersonalInformation.page.ts
> +    return this.photo.sendKeys(photoAbsolutePath);
no estoy tan seguro que así te funcione, puedes colocar una imagen que me compruebe que esto si funciona?

2017-10-12 12:09 UTC, aperdomob commented on test/IFrame.spec.ts
>  describe('Given the iFrame Page', () => {
los cambios relacionados con el iframe no los entiendo

2017-10-13 14:52 UTC, svillegasz commented on src/page/IFrame.page.ts
> +import { $, ElementFinder, browser, promise } from 'protractor';
estos cambios fue porque de la correcion que me habias hecho sobre cambias iframe1 por formFrame se me habia pasado cambiarlo en algunos metodos.

2017-10-13 14:52 UTC, svillegasz commented on src/page/PersonalInformation.page.ts
> +  private get photo(): ElementFinder {
Fixed

2017-10-13 14:57 UTC, svillegasz commented on src/page/PersonalInformation.page.ts
> +    return this.photo.sendKeys(photoAbsolutePath);
![giphy](https://user-images.githubusercontent.com/30663053/31552397-fae90012-affc-11e7-8feb-743a78b4a06d.gif)

2017-10-13 15:02 UTC, svillegasz commented on test/IFrame.spec.ts
>  describe('Given the iFrame Page', () => {
Alejo es que no entiendo porque se muestran esstos cambios otra vez, pero si te fijas con el ultimo PR https://github.com/svillegasz/protractor-workshop-2017/pull/21 son los mismo cambios

2017-10-13 15:33 UTC, aperdomob approved these changes

2017-10-13 15:41 UTC, aperdomob commented on test/IFrame.spec.ts
>  describe('Given the iFrame Page', () => {
revisa porque no debería mostrarte esos cambios, algo debes tener mal

2017-10-13 15:58 UTC, merged