Linter
svillegasz/protractor-workshop-2017 pull request #8
Opened 2017-10-04 21:11 UTC by svillegasz

2017-10-04 22:52 UTC, aperdomob requested changes

2017-10-04 22:52 UTC, aperdomob commented on tslint.json
> +}
EOF

2017-10-05 17:04 UTC, jhenaoz submitted a review, later dismissed
pusiste a escanear la carpeta protrac en lugar de protractor

2017-10-05 17:04 UTC, jhenaoz commented on README.md
> +[![Build Status](https://travis-ci.org/svillegasz/psl-workshop-api-testing-js.svg?branch=master)](https://travis-ci.org/svillegasz/psl-workshop-api-testing-js)
👍

2017-10-05 17:04 UTC, jhenaoz commented on package.json
> +    "lint": "tslint --type-check --project tsconfig.json protract/**/*.ts test/**/*.ts src/**/*.ts",
TYPO:
cambiar `"lint": "tslint --type-check --project tsconfig.json protract/**/*.ts test/**/*.ts src/**/*.ts"`
por: `"lint": "tslint --type-check --project tsconfig.json protractor/**/*.ts test/**/*.ts src/**/*.ts"`

2017-10-05 18:35 UTC, aperdomob approved these changes

2017-10-05 19:16 UTC, svillegasz commented
@jhenaoz

2017-10-06 13:44 UTC, merged